version: '3'
services:

  # UI: http://127.0.0.1:5001/webui
  ipfs-daemon:
    image: 'ipfs/go-ipfs:v0.9.0'
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:6000"
    user: "ipfs"
    command: [ "daemon", "--enable-pubsub-experiment" ]
